name: brew test-bot

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test-bot:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15-intel, macos-26]
        include:
          - os: ubuntu-latest
            container: ghcr.io/homebrew/brew:main
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: read
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v5
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-rubygems-

      - run: brew test-bot --only-cleanup-before
      - run: brew test-bot --only-setup
      - name: Test tap syntax
        run: |
          tap_dir="$(brew --repository tacf/tap)"
          ignored_script="${RUNNER_TEMP}/update-formula.sh"
          mv "${tap_dir}/scripts/update-formula.sh" "${ignored_script}"
          trap 'mv "${ignored_script}" "${tap_dir}/scripts/update-formula.sh"' EXIT
          brew test-bot --only-tap-syntax
      - run: brew test-bot --only-formulae
